### ISSUE TITLE
Memory error while loading the numpy array

### ISSUE THREAD

**Issue by riti1302** [kamata1729/robustTemplateMatching#3]
Hi @kamata1729 !
I am using the code without cuda and cython and I am getting the following memory error. My system has 4GB RAM. Looking forward to your reply.

save features...
calc NCC...
Traceback (most recent call last):
  File "run.py", line 68, in <module>
    template, image, threshold=None, use_cython=args.use_cython)
  File "/home/ritika/Documents/robustTemplateMatching-master/FeatureExtractor.py", line 117, in __call__
    self.template_feature_map.numpy(), self.image_feature_map.numpy())
  File "/home/ritika/Documents/robustTemplateMatching-master/FeatureExtractor.py", line 69, in calc_NCC
    tmp = np.zeros((c, M.shape[-2] - h_f, M.shape[-1] - w_f, h_f, w_f))
MemoryError

**Comment by janggj68** [comment]
Hi, I have same problem.
Did you fix it ?

**Comment by Junny-han** [comment]
I also ran the code without cuda and cython.Surprisingly, I input three pictures of similar size,one succeeded, one showed that the process was killed, and the other reported an error "type error"。Have you ever encountered a similar situation？

**Comment by Arka161** [comment]
The error will be fixed if you use the code from my PR or my fork.
